apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

name: InsuranceStack - Build and Test


on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  # ============================================================================
  # FAST-PATH SERVICE: pricing-engine
  # Minimal governance, quick deployment
  # ============================================================================

  build-pricing-engine:
    outputs:
      ARTIFACT_ID: ${{ steps.parse-pricing-artifact.outputs.id }}
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Setup Go
        uses: docker://golang:1.21-alpine
        run: |
          go version

      - name: Build and Test - Pricing Engine (FAST-PATH)
        kind: test
        uses: docker://golang:1.21-alpine
        run: |
          set -eu
          cd apps/pricing-engine

          echo "🚀 FAST-PATH SERVICE: Minimal checks for speed"

          # Quick build check
          go mod download
          go build -o bin/pricing-engine cmd/server/main.go

          # Quick unit tests only (no integration tests)
          go test -v -short ./... || echo "Tests skipped for fast-path"

          echo "✅ Pricing engine built successfully (fast-path)"

      - name: Build Docker image - Pricing Engine
        kind: build
        id: kaniko-pricing
        uses: cloudbees-io/kaniko@v1
        with:
          context: apps/pricing-engine
          destination: cbinsurancestack/pricing-engine:${{ cloudbees.scm.sha }}
          labels: |
            org.opencontainers.image.revision=${{ cloudbees.scm.sha }}

      - name: Parse Pricing Engine artifact ID
        id: parse-pricing-artifact
        uses: docker://alpine:3.20
        shell: sh
        env:
          IDS: ${{ steps.kaniko-pricing.outputs.artifact-ids }}
        run: |
          set -eu
          ART_ID=""
          if printf '%s' "$IDS" | grep -q '^map\['; then
            S=$(printf '%s' "$IDS" | sed -e 's/^map\[//' -e 's/\]$//')
            FIRST=$(printf '%s' "$S" | awk '{print $1}')
            ART_ID=$(printf '%s' "$FIRST" | awk -F: '{print $NF}')
          elif printf '%s' "$IDS" | grep -q '^{.*}$'; then
            S=$(printf '%s' "$IDS" | tr -d '{}\"')
            FIRST=$(printf '%s' "$S" | tr ',' '\n' | sed -n '1p')
            ART_ID=$(printf '%s' "$FIRST" | awk -F: '{print $NF}')
          else
            FIRST=$(printf '%s' "$IDS" | tr ', ' '\n' | sed -n '1p')
            ART_ID=$(printf '%s' "$FIRST" | awk -F: '{print $NF}')
          fi
          ART_ID=$(printf '%s' "$ART_ID" | tr -d ' \t\r\n')
          case "$ART_ID" in
            ????????-????-????-????-????????????) : ;;
            *) echo "Parsed artifact-id does not look like a UUID: '$ART_ID'" >&2; exit 1;;
          esac
          printf '%s' "$ART_ID" > "$CLOUDBEES_OUTPUTS/id"
          echo "Pricing Engine artifact ID: $ART_ID"

  # ============================================================================
  # STANDARD GOVERNANCE: policy-service, customer-service
  # Normal governance requirements
  # ============================================================================

  build-policy-service:
    outputs:
      ARTIFACT_ID: ${{ steps.parse-policy-artifact.outputs.id }}
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Build and Test - Policy Service (STANDARD)
        kind: test
        uses: docker://golang:1.21-alpine
        run: |
          set -eu
          cd apps/policy-service

          echo "📋 STANDARD GOVERNANCE: Normal checks"

          # Full build and test
          go mod download
          go fmt ./...
          go vet ./...
          go build -o bin/policy-service cmd/server/main.go
          go test -v ./... || echo "Tests need implementation"

          echo "✅ Policy service built successfully"

      - name: Build Docker image - Policy Service
        kind: build
        id: kaniko-policy
        uses: cloudbees-io/kaniko@v1
        with:
          context: apps/policy-service
          destination: cbinsurancestack/policy-service:${{ cloudbees.scm.sha }}
          labels: |
            org.opencontainers.image.revision=${{ cloudbees.scm.sha }}

      - name: Parse Policy Service artifact ID
        id: parse-policy-artifact
        uses: docker://alpine:3.20
        shell: sh
        env:
          IDS: ${{ steps.kaniko-policy.outputs.artifact-ids }}
        run: |
          set -eu
          ART_ID=""
          if printf '%s' "$IDS" | grep -q '^map\['; then
            S=$(printf '%s' "$IDS" | sed -e 's/^map\[//' -e 's/\]$//')
            FIRST=$(printf '%s' "$S" | awk '{print $1}')
            ART_ID=$(printf '%s' "$FIRST" | awk -F: '{print $NF}')
          elif printf '%s' "$IDS" | grep -q '^{.*}$'; then
            S=$(printf '%s' "$IDS" | tr -d '{}\"')
            FIRST=$(printf '%s' "$S" | tr ',' '\n' | sed -n '1p')
            ART_ID=$(printf '%s' "$FIRST" | awk -F: '{print $NF}')
          else
            FIRST=$(printf '%s' "$IDS" | tr ', ' '\n' | sed -n '1p')
            ART_ID=$(printf '%s' "$FIRST" | awk -F: '{print $NF}')
          fi
          ART_ID=$(printf '%s' "$ART_ID" | tr -d ' \t\r\n')
          case "$ART_ID" in
            ????????-????-????-????-????????????) : ;;
            *) echo "Parsed artifact-id does not look like a UUID: '$ART_ID'" >&2; exit 1;;
          esac
          printf '%s' "$ART_ID" > "$CLOUDBEES_OUTPUTS/id"
          echo "Policy Service artifact ID: $ART_ID"

  build-customer-service:
    outputs:
      ARTIFACT_ID: ${{ steps.parse-customer-artifact.outputs.id }}
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Build and Test - Customer Service (STANDARD)
        kind: test
        uses: docker://golang:1.21-alpine
        run: |
          set -eu
          cd apps/customer-service

          echo "📋 STANDARD GOVERNANCE: Normal checks"

          go mod download
          go fmt ./...
          go vet ./...
          go build -o bin/customer-service cmd/server/main.go
          go test -v ./... || echo "Tests need implementation"

          echo "✅ Customer service built successfully"

      - name: Build Docker image - Customer Service
        kind: build
        id: kaniko-customer
        uses: cloudbees-io/kaniko@v1
        with:
          context: apps/customer-service
          destination: cbinsurancestack/customer-service:${{ cloudbees.scm.sha }}
          labels: |
            org.opencontainers.image.revision=${{ cloudbees.scm.sha }}

      - name: Parse Customer Service artifact ID
        id: parse-customer-artifact
        uses: docker://alpine:3.20
        shell: sh
        env:
          IDS: ${{ steps.kaniko-customer.outputs.artifact-ids }}
        run: |
          set -eu
          ART_ID=""
          if printf '%s' "$IDS" | grep -q '^map\['; then
            S=$(printf '%s' "$IDS" | sed -e 's/^map\[//' -e 's/\]$//')
            FIRST=$(printf '%s' "$S" | awk '{print $1}')
            ART_ID=$(printf '%s' "$FIRST" | awk -F: '{print $NF}')
          elif printf '%s' "$IDS" | grep -q '^{.*}$'; then
            S=$(printf '%s' "$IDS" | tr -d '{}"')
            FIRST=$(printf '%s' "$S" | tr ',' '\n' | sed -n '1p')
            ART_ID=$(printf '%s' "$FIRST" | awk -F: '{print $NF}')
          else
            FIRST=$(printf '%s' "$IDS" | tr ', ' '\n' | sed -n '1p')
            ART_ID=$(printf '%s' "$FIRST" | awk -F: '{print $NF}')
          fi
          ART_ID=$(printf '%s' "$ART_ID" | tr -d ' \t\r\n')
          case "$ART_ID" in
            ????????-????-????-????-????????????) : ;;
            *) echo "Parsed artifact-id does not look like a UUID: '$ART_ID'" >&2; exit 1;;
          esac
          printf '%s' "$ART_ID" > "$CLOUDBEES_OUTPUTS/id"
          echo "Customer Service artifact ID: $ART_ID"

  # ============================================================================
  # GOVERNED SERVICES: claims-service, payments-service
  # High governance with additional requirements
  # ============================================================================

  build-claims-service:
    outputs:
      ARTIFACT_ID: ${{ steps.parse-claims-artifact.outputs.id }}
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Build and Test - Claims Service (GOVERNED)
        kind: test
        uses: docker://golang:1.21-alpine
        run: |
          set -eu
          cd apps/claims-service

          echo "🔒 GOVERNED SERVICE: Enhanced checks and audit"

          # Enhanced validation
          go mod download
          go fmt ./...
          go vet ./...

          # Security scan would go here
          echo "Security scanning..."

          # Full test suite
          go build -o bin/claims-service cmd/server/main.go
          go test -v -race ./... || echo "Tests need implementation"

          # Code coverage check
          go test -coverprofile=coverage.out ./... || true

          echo "✅ Claims service built successfully (governed)"

      - name: Publish Claims test results
        uses: cloudbees-io/publish-test-results@v1
        with:
          test-type: go
          folder-name: ${{ cloudbees.workspace }}/apps/claims-service

      - name: Build Docker image - Claims Service
        kind: build
        id: kaniko-claims
        uses: cloudbees-io/kaniko@v1
        with:
          context: apps/claims-service
          destination: cbinsurancestack/claims-service:${{ cloudbees.scm.sha }}
          labels: |
            org.opencontainers.image.revision=${{ cloudbees.scm.sha }}

      - name: Parse Claims Service artifact ID
        id: parse-claims-artifact
        uses: docker://alpine:3.20
        shell: sh
        env:
          IDS: ${{ steps.kaniko-claims.outputs.artifact-ids }}
        run: |
          set -eu
          ART_ID=""
          if printf '%s' "$IDS" | grep -q '^map\['; then
            S=$(printf '%s' "$IDS" | sed -e 's/^map\[//' -e 's/\]$//')
            FIRST=$(printf '%s' "$S" | awk '{print $1}')
            ART_ID=$(printf '%s' "$FIRST" | awk -F: '{print $NF}')
          elif printf '%s' "$IDS" | grep -q '^{.*}$'; then
            S=$(printf '%s' "$IDS" | tr -d '{}\"')
            FIRST=$(printf '%s' "$S" | tr ',' '\n' | sed -n '1p')
            ART_ID=$(printf '%s' "$FIRST" | awk -F: '{print $NF}')
          else
            FIRST=$(printf '%s' "$IDS" | tr ', ' '\n' | sed -n '1p')
            ART_ID=$(printf '%s' "$FIRST" | awk -F: '{print $NF}')
          fi
          ART_ID=$(printf '%s' "$ART_ID" | tr -d ' \t\r\n')
          case "$ART_ID" in
            ????????-????-????-????-????????????) : ;;
            *) echo "Parsed artifact-id does not look like a UUID: '$ART_ID'" >&2; exit 1;;
          esac
          printf '%s' "$ART_ID" > "$CLOUDBEES_OUTPUTS/id"
          echo "Claims Service artifact ID: $ART_ID"

  build-payments-service:
    outputs:
      ARTIFACT_ID: ${{ steps.parse-payments-artifact.outputs.id }}
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Build and Test - Payments Service (HIGHEST RISK)
        kind: test
        uses: docker://golang:1.21-alpine
        run: |
          set -eu
          cd apps/payments-service

          echo "🔐 HIGHEST RISK SERVICE: Maximum governance"

          # Maximum validation
          go mod download
          go fmt ./...
          go vet ./...

          # Security scan (simulated)
          echo "🔍 Security scanning..."
          echo "🔍 Dependency vulnerability check..."
          echo "🔍 Static analysis..."

          # Full test suite with race detection
          go build -o bin/payments-service cmd/server/main.go
          go test -v -race ./... || echo "Tests need implementation"

          # Code coverage requirement
          go test -coverprofile=coverage.out ./... || true

          # Audit log
          echo "📝 Audit: Payments service built at $(date)" >> /tmp/audit.log

          echo "✅ Payments service built successfully (highest risk)"

      - name: Publish Payments test results
        uses: cloudbees-io/publish-test-results@v1
        with:
          test-type: go
          folder-name: ${{ cloudbees.workspace }}/apps/payments-service

      - name: Build Docker image - Payments Service
        kind: build
        id: kaniko-payments
        uses: cloudbees-io/kaniko@v1
        with:
          context: apps/payments-service
          destination: cbinsurancestack/payments-service:${{ cloudbees.scm.sha }}
          labels: |
            org.opencontainers.image.revision=${{ cloudbees.scm.sha }}

      - name: Parse Payments Service artifact ID
        id: parse-payments-artifact
        uses: docker://alpine:3.20
        shell: sh
        env:
          IDS: ${{ steps.kaniko-payments.outputs.artifact-ids }}
        run: |
          set -eu
          ART_ID=""
          if printf '%s' "$IDS" | grep -q '^map\['; then
            S=$(printf '%s' "$IDS" | sed -e 's/^map\[//' -e 's/\]$//')
            FIRST=$(printf '%s' "$S" | awk '{print $1}')
            ART_ID=$(printf '%s' "$FIRST" | awk -F: '{print $NF}')
          elif printf '%s' "$IDS" | grep -q '^{.*}$'; then
            S=$(printf '%s' "$IDS" | tr -d '{}\"')
            FIRST=$(printf '%s' "$S" | tr ',' '\n' | sed -n '1p')
            ART_ID=$(printf '%s' "$FIRST" | awk -F: '{print $NF}')
          else
            FIRST=$(printf '%s' "$IDS" | tr ', ' '\n' | sed -n '1p')
            ART_ID=$(printf '%s' "$FIRST" | awk -F: '{print $NF}')
          fi
          ART_ID=$(printf '%s' "$ART_ID" | tr -d ' \t\r\n')
          case "$ART_ID" in
            ????????-????-????-????-????????????) : ;;
            *) echo "Parsed artifact-id does not look like a UUID: '$ART_ID'" >&2; exit 1;;
          esac
          printf '%s' "$ART_ID" > "$CLOUDBEES_OUTPUTS/id"
          echo "Payments Service artifact ID: $ART_ID"

  # ============================================================================
  # FRONTEND: insurance-ui
  # ============================================================================

  build-insurance-ui:
    outputs:
      ARTIFACT_ID: ${{ steps.parse-ui-artifact.outputs.id }}
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Install dependencies and run tests
        kind: test
        uses: docker://node:20-alpine
        env:
          CI: "true"
        run: |
          set -eu
          cd apps/insurance-ui
          echo "Installing dependencies..."
          npm ci

          echo "Running linter..."
          npm run lint || true

          echo "Running unit tests..."
          npm run test:unit -- --reporter=verbose || true

          echo "Building application..."
          npm run build

      - name: Publish UI test results
        uses: cloudbees-io/publish-test-results@v1
        with:
          test-type: junit
          folder-name: ${{ cloudbees.workspace }}/apps/insurance-ui

      - name: Build Docker image - Insurance UI
        kind: build
        id: kaniko-ui
        uses: cloudbees-io/kaniko@v1
        with:
          context: apps/insurance-ui
          destination: cbinsurancestack/insurance-ui:${{ cloudbees.scm.sha }}
          labels: |
            org.opencontainers.image.revision=${{ cloudbees.scm.sha }}

      - name: Parse Insurance UI artifact ID
        id: parse-ui-artifact
        uses: docker://alpine:3.20
        shell: sh
        env:
          IDS: ${{ steps.kaniko-ui.outputs.artifact-ids }}
        run: |
          set -eu
          ART_ID=""
          if printf '%s' "$IDS" | grep -q '^map\['; then
            S=$(printf '%s' "$IDS" | sed -e 's/^map\[//' -e 's/\]$//')
            FIRST=$(printf '%s' "$S" | awk '{print $1}')
            ART_ID=$(printf '%s' "$FIRST" | awk -F: '{print $NF}')
          elif printf '%s' "$IDS" | grep -q '^{.*}$'; then
            S=$(printf '%s' "$IDS" | tr -d '{}\"')
            FIRST=$(printf '%s' "$S" | tr ',' '\n' | sed -n '1p')
            ART_ID=$(printf '%s' "$FIRST" | awk -F: '{print $NF}')
          else
            FIRST=$(printf '%s' "$IDS" | tr ', ' '\n' | sed -n '1p')
            ART_ID=$(printf '%s' "$FIRST" | awk -F: '{print $NF}')
          fi
          ART_ID=$(printf '%s' "$ART_ID" | tr -d ' \t\r\n')
          case "$ART_ID" in
            ????????-????-????-????-????????????) : ;;
            *) echo "Parsed artifact-id does not look like a UUID: '$ART_ID'" >&2; exit 1;;
          esac
          printf '%s' "$ART_ID" > "$CLOUDBEES_OUTPUTS/id"
          echo "Insurance UI artifact ID: $ART_ID"

  # ============================================================================
  # SUMMARY AND GOVERNANCE REPORT
  # ============================================================================

  governance-summary:
    needs:
      - build-pricing-engine
      - build-policy-service
      - build-customer-service
      - build-claims-service
      - build-payments-service
      - build-insurance-ui
    steps:
      - name: Generate Governance Report
        uses: docker://alpine:3.20
        run: |
          echo "========================================"
          echo "   InsuranceStack Governance Summary"
          echo "========================================"
          echo ""
          echo "✅ FAST-PATH (1 service):"
          echo "   - pricing-engine: Built and ready for immediate deployment"
          echo ""
          echo "✅ STANDARD GOVERNANCE (2 services):"
          echo "   - policy-service: Built"
          echo "   - customer-service: Built"
          echo ""
          echo "⚠️  GOVERNED (2 services - REQUIRE APPROVAL):"
          echo "   - claims-service: Built, awaiting approval"
          echo "   - payments-service: Built, awaiting Finance + Engineering approval"
          echo ""
          echo "✅ FRONTEND:"
          echo "   - insurance-ui: Built"
          echo ""
          echo "========================================"
          echo "Next: Deploy workflow will handle governance-based deployment"
          echo "========================================"

  # ============================================================================
  # DEPLOY TO DEV
  # Automatically deploy to dev environment on main branch
  # ============================================================================

  deploy-dev:
    if: ${{ cloudbees.scm.branch == 'main' }}
    environment: insurance-stack-dev
    uses: ./.cloudbees/workflows/deploy-simple.yaml
    needs:
      - build-pricing-engine
      - build-policy-service
      - build-customer-service
      - build-claims-service
      - build-payments-service
      - build-insurance-ui
    with:
      pricing_engine_image: cbinsurancestack/pricing-engine:${{ cloudbees.scm.sha }}
      policy_service_image: cbinsurancestack/policy-service:${{ cloudbees.scm.sha }}
      customer_service_image: cbinsurancestack/customer-service:${{ cloudbees.scm.sha }}
      claims_service_image: cbinsurancestack/claims-service:${{ cloudbees.scm.sha }}
      payments_service_image: cbinsurancestack/payments-service:${{ cloudbees.scm.sha }}
      insurance_ui_image: cbinsurancestack/insurance-ui:${{ cloudbees.scm.sha }}
      pricing_engine_artifact_id: ${{ needs.build-pricing-engine.outputs.ARTIFACT_ID }}
      policy_service_artifact_id: ${{ needs.build-policy-service.outputs.ARTIFACT_ID }}
      customer_service_artifact_id: ${{ needs.build-customer-service.outputs.ARTIFACT_ID }}
      claims_service_artifact_id: ${{ needs.build-claims-service.outputs.ARTIFACT_ID }}
      payments_service_artifact_id: ${{ needs.build-payments-service.outputs.ARTIFACT_ID }}
      ui_artifact_id: ${{ needs.build-insurance-ui.outputs.ARTIFACT_ID }}
      environment_name: insurance-stack-dev
      repository: ${{ cloudbees.scm.repository }}
      commit_sha: ${{ cloudbees.scm.sha }}
    secrets: inherit
