apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Deploy InsuranceStack

on:
  workflow_call:
    inputs:
      pricing_engine_image:
        type: string
        required: true
      policy_service_image:
        type: string
        required: true
      customer_service_image:
        type: string
        required: true
      claims_service_image:
        type: string
        required: true
      payments_service_image:
        type: string
        required: true
      insurance_ui_image:
        type: string
        required: true
      pricing_engine_artifact_id:
        type: string
        required: true
      policy_service_artifact_id:
        type: string
        required: true
      customer_service_artifact_id:
        type: string
        required: true
      claims_service_artifact_id:
        type: string
        required: true
      payments_service_artifact_id:
        type: string
        required: true
      ui_artifact_id:
        type: string
        required: true
      environment_name:
        type: string
        required: true
      commit_sha:
        type: string
        required: true
      repository:
        type: string
        required: true

jobs:
  deploy:
    environment: ${{ inputs.environment_name }}

    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Extract organization from repository
        id: org
        uses: docker://alpine:3.20
        shell: sh
        env:
          REPOSITORY: ${{ inputs.repository }}
        run: |
          set -eu
          # Extract owner from repository (format: owner/repo)
          ORG=$(echo "$REPOSITORY" | cut -d'/' -f1)
          echo "Organization: $ORG"
          printf '%s' "$ORG" > "$CLOUDBEES_OUTPUTS/name"

      - name: Build deployment metadata
        id: metadata
        uses: docker://alpine:3.20
        shell: sh
        env:
          COMMIT_SHA: ${{ inputs.commit_sha }}
          ENVIRONMENT_NAME: ${{ inputs.environment_name }}
        run: |
          set -eu

          # Short SHA (12 chars)
          SHORT_SHA=$(echo "$COMMIT_SHA" | cut -c1-12)
          printf '%s' "$SHORT_SHA" > "$CLOUDBEES_OUTPUTS/sha12"
          echo "Short SHA: $SHORT_SHA"

          # Short version (first 7 chars of SHA)
          SHORT_VER=$(echo "$COMMIT_SHA" | cut -c1-7)
          printf '%s' "$SHORT_VER" > "$CLOUDBEES_OUTPUTS/ver"
          echo "Version: $SHORT_VER"

          # Timestamp
          TIMESTAMP=$(date -u +%Y%m%d%H%M%S)
          printf '%s' "$TIMESTAMP" > "$CLOUDBEES_OUTPUTS/ts"
          echo "Timestamp: $TIMESTAMP"

          # Environment code (shortened for labels)
          case "$ENVIRONMENT_NAME" in
            insurance-stack-dev)
              ENV_CODE="dev"
              ;;
            insurance-stack-staging)
              ENV_CODE="staging"
              ;;
            insurance-stack-prod)
              ENV_CODE="prod"
              ;;
            *)
              # Use first 8 chars of environment name
              ENV_CODE=$(echo "$ENVIRONMENT_NAME" | cut -c1-8)
              ;;
          esac
          printf '%s' "$ENV_CODE" > "$CLOUDBEES_OUTPUTS/code"
          echo "Environment code: $ENV_CODE"

      - name: Deploy InsuranceStack
        uses: docker://alpine:3.20
        run: |
          echo "========================================"
          echo "   InsuranceStack Deployment"
          echo "========================================"
          echo ""
          echo "Environment: ${{ inputs.environment_name }}"
          echo "Commit SHA: ${{ inputs.commit_sha }}"
          echo "Organization: ${{ steps.org.outputs.name }}"
          echo ""
          echo "Images:"
          echo "  - Pricing Engine: ${{ inputs.pricing_engine_image }}"
          echo "  - Policy Service: ${{ inputs.policy_service_image }}"
          echo "  - Customer Service: ${{ inputs.customer_service_image }}"
          echo "  - Claims Service: ${{ inputs.claims_service_image }}"
          echo "  - Payments Service: ${{ inputs.payments_service_image }}"
          echo "  - Insurance UI: ${{ inputs.insurance_ui_image }}"
          echo ""
          echo "✅ Deployment simulated successfully"
          echo "========================================"

      - name: Register Pricing Engine artifact
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: ${{ inputs.pricing_engine_artifact_id }}
          target-environment: ${{ inputs.environment_name }}
          labels: >
            ver=${{ steps.metadata.outputs.ver }},
            sha=${{ steps.metadata.outputs.sha12 }},
            ts=${{ steps.metadata.outputs.ts }},
            d.${{ steps.metadata.outputs.code }}=true

      - name: Register Policy Service artifact
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: ${{ inputs.policy_service_artifact_id }}
          target-environment: ${{ inputs.environment_name }}
          labels: >
            ver=${{ steps.metadata.outputs.ver }},
            sha=${{ steps.metadata.outputs.sha12 }},
            ts=${{ steps.metadata.outputs.ts }},
            d.${{ steps.metadata.outputs.code }}=true

      - name: Register Customer Service artifact
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: ${{ inputs.customer_service_artifact_id }}
          target-environment: ${{ inputs.environment_name }}
          labels: >
            ver=${{ steps.metadata.outputs.ver }},
            sha=${{ steps.metadata.outputs.sha12 }},
            ts=${{ steps.metadata.outputs.ts }},
            d.${{ steps.metadata.outputs.code }}=true

      - name: Register Claims Service artifact
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: ${{ inputs.claims_service_artifact_id }}
          target-environment: ${{ inputs.environment_name }}
          labels: >
            ver=${{ steps.metadata.outputs.ver }},
            sha=${{ steps.metadata.outputs.sha12 }},
            ts=${{ steps.metadata.outputs.ts }},
            d.${{ steps.metadata.outputs.code }}=true

      - name: Register Payments Service artifact
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: ${{ inputs.payments_service_artifact_id }}
          target-environment: ${{ inputs.environment_name }}
          labels: >
            ver=${{ steps.metadata.outputs.ver }},
            sha=${{ steps.metadata.outputs.sha12 }},
            ts=${{ steps.metadata.outputs.ts }},
            d.${{ steps.metadata.outputs.code }}=true

      - name: Register Insurance UI artifact
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: ${{ inputs.ui_artifact_id }}
          target-environment: ${{ inputs.environment_name }}
          labels: >
            ver=${{ steps.metadata.outputs.ver }},
            sha=${{ steps.metadata.outputs.sha12 }},
            ts=${{ steps.metadata.outputs.ts }},
            d.${{ steps.metadata.outputs.code }}=true

      - name: Publish deployment evidence
        kind: deploy
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          format: MARKDOWN
          content: |
            ## Deployed: InsuranceStack (All Components)

            **Environment:** `${{ inputs.environment_name }}`
            **Repository:** `${{ inputs.repository }}`
            **Commit:** `${{ inputs.commit_sha }}`

            ### Components Deployed
            - **Pricing Engine:** `${{ inputs.pricing_engine_image }}`
            - **Policy Service:** `${{ inputs.policy_service_image }}`
            - **Customer Service:** `${{ inputs.customer_service_image }}`
            - **Claims Service:** `${{ inputs.claims_service_image }}`
            - **Payments Service:** `${{ inputs.payments_service_image }}`
            - **Insurance UI:** `${{ inputs.insurance_ui_image }}`

            ### Deployment Details
            - Environment: `${{ inputs.environment_name }}`
            - Organization: `${{ steps.org.outputs.name }}`
            - Deployment successful ✓
